#!/bin/bash
set -o errexit -o pipefail -o noclobber -o nounset

get-qmmander() {
    IS_VERBOSE=false

    _QMMANDER_HOME=/opt/qmannder

    _install_or_update() {
        [ ! -d "${_QMMANDER_HOME}" ] && mkdir "${_QMMANDER_HOME}";

        if [ -d "${_QMMANDER_HOME}" ]; then
            rm -rf "${_QMMANDER_HOME:?}/*" # prevent expansion to /*
            tar -xf "${1}" -C "${_QMMANDER_HOME}"
            chmod +x "${_QMMANDER_HOME}/qmmander.sh"

            ln -s "${_QMMANDER_HOME}/qmmander.sh" /usr/local/bin/qmmander
        else
            printf "Unable to create qammnder home, please check permissions."
        fi
    }


    usage() {
        printf -v text "%s" \
            "get-qmmander downloads qmmander-cli to the current directory; ask for the nexus bot token if NEXUS_BOT_TOKEN is not set as environmental variable [OPTION...]\n" \
            "    -v, --verbose        shows more info\n" \
            "    -u, --update         updates qmmander cli \n" \
            "    -h, --help           shows this help message\n" \
            "    -r, --release-tag    cli release tag, e.g. 0.1.12, default: latest\n"
        echo -e "$text"
    }

    OPTS=$(getopt -o vduhr: --long verbose,debug,help,update,release-tag: -- "$@")
    if [ $? != 0 ] ; then echo "Failed parsing options." >&2 ; exit 1 ; fi

    eval set -- "$OPTS"

    while true; do
        case "$1" in
            -v | --verbose )
                IS_VERBOSE=true
                shift ;;
            -u | --update )
                UPDATE_USR_BIN=true
                shift ;;
            -r | --release-tag )
                RELEASE=$2
                shift 2 ;;
            -h | --help )
                usage
                return
                ;;
            -- )
                shift
                break ;;
            * )
                break ;;
        esac
    done

    if [ -z "${NEXUS_BOT_TOKEN:''}" ]; then
        printf "Missing env NEXUS_BOT_TOKEN. The nexus bot token is required, please insert:\n"
        read -r TOKEN
        if [ -z "$TOKEN" ]; then
            exit 1
        fi
    else
        TOKEN="$NEXUS_BOT_TOKEN"
    fi

    if [ -z "${RELEASE:''}" ]; then
        printf "Missing release version. The release version to be installed is required, plase insert:\n"
        read -r RELEASE
        if [ -z "$RELEASE" ]; then
            exit 1
        fi
    fi

    qmmanderDestionationPath="/tmp/qmmander-$(date +%s).tar.gz"
    cmd=$(curl -s -f -u "bot-ro:${TOKEN}" \
        "https://nexus.modac.cloud/repository/qwiki-raw-private/qmmander-cli/${RELEASE}/qmannder.tar.gz" \
        --output "$qmmanderDestionationPath")

    if [[ "$cmd" -ne "0" ]]; then
        printf "\n[ERROR] NEXUS_BOT_TOKEN or RELEASE version invalid. Unable to fetch qmmander cli.\n"
        exit 1
    fi

    unset TOKEN RELEASE

    if [ -n "$UPDATE_USR_BIN" ]; then
        $IS_VERBOSE && printf "replacing current installation of qmmander\n"
        _install_or_update "$qmmanderDestionationPath";
    else
        $IS_VERBOSE && printf "Update flag not set, not replacing qmmander\n"
    fi

    printf "\ndone\n"

}

get-qmmander "$@"
